spring:
  datasource:
    url: jdbc:h2:mem:./nunus-sports
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2

  springdoc:
    swagger-ui:
        path: /swagger-ui.html